import json

transcript_path = r"C:\Users\lap4all\.gemini\antigravity-ide\brain\99fae90b-413f-4302-ba67-0dea689b73b1\.system_generated\logs\transcript.jsonl"

try:
    with open(transcript_path, 'r', encoding='utf-8') as f:
        for line in f:
            obj = json.loads(line)
            # Find if this step is console logs output
            content = obj.get("content", "")
            if content and ("Console Log" in content or "console.log" in content or "console_logs" in content or "Error" in content):
                # Check if it was generated by the browser subagent execution
                if len(content) > 50 and "PageId" in str(obj):
                    print(f"Step {obj.get('step_index')}: {obj.get('type')}")
                    print("Content:\n", content)
                    print("="*80)
except Exception as e:
    print("Error:", str(e))
